name: Library
on:
  push:
    # paths: "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install deps
        run: pnpm install

      - name: Build packages
        run: pnpm --filter "./packages/**" -r build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: packages/*/dist*/

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: packages

      - name: Lint packages
        run: pnpm --filter "./packages/**" -r lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: packages

      - name: Test packages
        run: pnpm --filter "./packages/**" -r test

  publish:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - run: pnpm install
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: packages
      - name: Git status (debug)
        run: git status

      - name: Publish packages
        run: pnpm publish -r --filter "./packages/**" --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
