name: "library"
on:
  push:
    paths: "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install deps
        run: pnpm install

      - name: Build packages
        run: pnpm --filter "./packages/**" -r build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: packages/*/dist/

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Lint packages
        run: pnpm --filter "./packages/**" -r lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - name: Install deps
        run: pnpm install
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Test packages
        run: pnpm --filter "./packages/**" -r test
