name: "Test and build library"
on:
  push:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Test library
        run: pnpm test:lib

      - name: Build library
        run: pnpm build:lib
