name: "Lint/test/build library"
on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Lint packages
        run: pnpm -r lint

      - name: Test packages
        run: pnpm -r test

      - name: Build packages
        run: pnpm -r build
